@helpers.sql

DECLARE
v_sql CLOB := q'[
    CREATE TABLE t_ds_trigger_relation (
      id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      trigger_type   NUMBER          NOT NULL,
      trigger_code   NUMBER(19)      NOT NULL,
      job_id         NUMBER(19)      NOT NULL,
      create_time    TIMESTAMP       ,
      update_time    TIMESTAMP       ,
      CONSTRAINT t_ds_trigger_relation_pk PRIMARY KEY (id),
      CONSTRAINT t_ds_trigger_relation_uq UNIQUE (trigger_type,job_id,trigger_code)
    )
  ]';
BEGIN
  create_table_if_not_exists('t_ds_trigger_relation', v_sql);
END;

DECLARE
v_sql CLOB := q'[
    CREATE TABLE t_ds_relation_sub_workflow (
      id                         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      parent_workflow_instance_id NUMBER(19) NOT NULL,
      parent_task_code            NUMBER(19) NOT NULL,
      sub_workflow_instance_id    NUMBER(19) NOT NULL,
      CONSTRAINT t_ds_rel_sub_wf_pk PRIMARY KEY (id)
    )
  ]';
BEGIN
  create_table_if_not_exists('t_ds_relation_sub_workflow', v_sql);
END;

BEGIN
  rename_table_if_exists('t_ds_fav', 't_ds_fav_task');
END;

DECLARE
v_sql CLOB := q'[
    CREATE TABLE t_ds_fav_task (
      id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      task_type VARCHAR2(64)  NOT NULL,
      user_id   NUMBER        NOT NULL,
      CONSTRAINT t_ds_fav_task_pk PRIMARY KEY (id)
    )
  ]';
BEGIN
  create_table_if_not_exists('t_ds_fav_task', v_sql);
END;

DECLARE
v_sql CLOB := q'[
    CREATE TABLE t_ds_project_preference (
      id           NUMBER,
      code         NUMBER(19) NOT NULL,
      project_code NUMBER(19) NOT NULL,
      preferences  VARCHAR2(512) NOT NULL,
      user_id      NUMBER       ,
      state        NUMBER DEFAULT 1,
      create_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      update_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT t_ds_proj_pref_pk PRIMARY KEY (id)
    )
  ]';
BEGIN
  create_table_if_not_exists('t_ds_project_preference', v_sql);
END;

DECLARE
v_sql CLOB := q'[
    CREATE TABLE t_ds_project_parameter (
      id           NUMBER,
      param_name   VARCHAR2(255) NOT NULL,
      param_value  VARCHAR2(255) NOT NULL,
      code         NUMBER(19)    NOT NULL,
      project_code NUMBER(19)    NOT NULL,
      user_id      NUMBER        ,
      create_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      update_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT t_ds_proj_param_pk PRIMARY KEY (id)
    )
  ]';
BEGIN
  create_table_if_not_exists('t_ds_project_parameter', v_sql);
END;

BEGIN
  add_column_if_not_exists('t_ds_task_definition',      'is_cache', 'is_cache NUMBER(1) DEFAULT 0');
  add_column_if_not_exists('t_ds_task_definition_log',  'is_cache', 'is_cache NUMBER(1) DEFAULT 0');
  add_column_if_not_exists('t_ds_task_instance',        'is_cache', 'is_cache NUMBER(1) DEFAULT 0');
  add_column_if_not_exists('t_ds_task_instance',        'cache_key','cache_key VARCHAR2(200)');
  
  add_column_if_not_exists('t_ds_process_definition',      'execution_type','execution_type NUMBER DEFAULT 0');
  add_column_if_not_exists('t_ds_process_definition_log',  'execution_type','execution_type NUMBER DEFAULT 0');
  add_column_if_not_exists('t_ds_process_instance',        'next_process_instance_id','next_process_instance_id NUMBER');
  
  add_column_if_not_exists('t_ds_task_instance','process_instance_name','process_instance_name VARCHAR2(255)');
  add_column_if_not_exists('t_ds_task_instance','executor_name','executor_name VARCHAR2(64)');
  add_column_if_not_exists('t_ds_task_instance','test_flag','test_flag NUMBER(1)');
  add_column_if_not_exists('t_ds_task_instance','project_code','project_code NUMBER(19)');
  
  add_column_if_not_exists('t_ds_process_instance','project_code','project_code NUMBER(19)');
  add_column_if_not_exists('t_ds_process_instance','executor_name','executor_name VARCHAR2(64)');
  add_column_if_not_exists('t_ds_process_instance','tenant_code','tenant_code VARCHAR2(64)');
  add_column_if_not_exists('t_ds_process_instance','test_flag','test_flag NUMBER(1)');
  
  add_column_if_not_exists('t_ds_command','tenant_code','tenant_code VARCHAR2(64)');
  add_column_if_not_exists('t_ds_command','test_flag','test_flag NUMBER(1)');
  add_column_if_not_exists('t_ds_command','worker_group','worker_group VARCHAR2(255)');
  
  add_column_if_not_exists('t_ds_error_command','tenant_code','tenant_code VARCHAR2(64)');
  add_column_if_not_exists('t_ds_error_command','test_flag','test_flag NUMBER(1)');
  
  add_column_if_not_exists('t_ds_schedules','tenant_code','tenant_code VARCHAR2(64)');
  add_column_if_not_exists('t_ds_schedules','worker_group','worker_group VARCHAR2(255)');
  
  add_column_if_not_exists('t_ds_alert','title','title VARCHAR2(512)');
  add_column_if_not_exists('t_ds_project','name','name VARCHAR2(255)');
  
  add_column_if_not_exists('t_ds_task_instance','worker_group','worker_group VARCHAR2(255)');
  add_column_if_not_exists('t_ds_udfs','func_name','func_name VARCHAR2(255)');
  add_column_if_not_exists('t_ds_version','version','version VARCHAR2(63)');
  add_column_if_not_exists('t_ds_plugin_define','plugin_name','plugin_name VARCHAR2(255)');
  add_column_if_not_exists('t_ds_plugin_define','plugin_type','plugin_type VARCHAR2(63)');
  add_column_if_not_exists('t_ds_alert_plugin_instance','instance_name','instance_name VARCHAR2(255)');
  add_column_if_not_exists('t_ds_dq_rule','name','name VARCHAR2(255)');
  add_column_if_not_exists('t_ds_environment','name','name VARCHAR2(255)');
  add_column_if_not_exists('t_ds_task_group_queue','task_name','task_name VARCHAR2(255)');
  add_column_if_not_exists('t_ds_task_group','name','name VARCHAR2(255)');
  add_column_if_not_exists('t_ds_k8s','k8s_name','k8s_name VARCHAR2(255)');
  add_column_if_not_exists('t_ds_k8s_namespace','namespace','namespace VARCHAR2(255)');
  add_column_if_not_exists('t_ds_cluster','name','name VARCHAR2(255)');
END;

ALTER TABLE t_ds_alert                MODIFY (title              VARCHAR2(512));
ALTER TABLE t_ds_alert_plugin_instance MODIFY (instance_name     VARCHAR2(255));
ALTER TABLE t_ds_cluster               MODIFY (name              VARCHAR2(255));

ALTER TABLE t_ds_command               MODIFY (worker_group      VARCHAR2(255));
ALTER TABLE t_ds_command               MODIFY (tenant_code       DEFAULT 'default');

ALTER TABLE t_ds_error_command         MODIFY (worker_group      VARCHAR2(255));
ALTER TABLE t_ds_error_command         MODIFY (tenant_code       DEFAULT 'default');

ALTER TABLE t_ds_k8s                   MODIFY (k8s_name          VARCHAR2(255));

ALTER TABLE t_ds_k8s_namespace         MODIFY (namespace         VARCHAR2(255));
ALTER TABLE t_ds_k8s_namespace         MODIFY (code              DEFAULT NULL);
ALTER TABLE t_ds_k8s_namespace         MODIFY (cluster_code      DEFAULT NULL);

ALTER TABLE t_ds_plugin_define         MODIFY (plugin_name       VARCHAR2(255));
ALTER TABLE t_ds_plugin_define         MODIFY (plugin_type       VARCHAR2(63));

ALTER TABLE t_ds_process_instance      MODIFY (worker_group      VARCHAR2(255));
ALTER TABLE t_ds_process_instance      MODIFY (executor_name     DEFAULT NULL);
ALTER TABLE t_ds_process_instance      MODIFY (tenant_code       DEFAULT 'default');

ALTER TABLE t_ds_project               MODIFY (name              VARCHAR2(255));

ALTER TABLE t_ds_schedules             MODIFY (worker_group      VARCHAR2(255));
ALTER TABLE t_ds_schedules             MODIFY (tenant_code       DEFAULT 'default');

ALTER TABLE t_ds_task_group            MODIFY (name              VARCHAR2(255));
ALTER TABLE t_ds_task_group_queue      MODIFY (task_name         VARCHAR2(255));

ALTER TABLE t_ds_task_instance         MODIFY (worker_group      VARCHAR2(255));
ALTER TABLE t_ds_task_instance         MODIFY (process_instance_name DEFAULT NULL);
ALTER TABLE t_ds_task_instance         MODIFY (executor_name     DEFAULT NULL);
ALTER TABLE t_ds_task_instance         MODIFY (project_code      NUMBER(19));

ALTER TABLE t_ds_udfs                  MODIFY (func_name         VARCHAR2(255));

ALTER TABLE t_ds_user                  MODIFY (tenant_id         DEFAULT -1);

ALTER TABLE t_ds_version               MODIFY (version           VARCHAR2(63));

ALTER TABLE t_ds_worker_group          MODIFY (description       CLOB);

ALTER TABLE t_ds_error_command    MODIFY (id               DEFAULT NULL);
ALTER TABLE t_ds_task_instance    MODIFY (log_path         DEFAULT NULL);

BEGIN
  drop_index_if_exists('idx_code');
  drop_index_if_exists('idx_process_code_version');
  drop_index_if_exists('idx_code_version');
  drop_index_if_exists('task_definition_index');

  create_index_if_not_exists('idx_cache_key',
    'CREATE INDEX idx_cache_key ON t_ds_task_instance (cache_key)');

  create_index_if_not_exists('idx_parent_workflow_instance_id',
    'CREATE INDEX idx_parent_workflow_instance_id ON t_ds_relation_sub_workflow (parent_workflow_instance_id)');

  create_index_if_not_exists('idx_parent_task_code',
    'CREATE INDEX idx_parent_task_code ON t_ds_relation_sub_workflow (parent_task_code)');

  create_index_if_not_exists('idx_sub_workflow_instance_id',
    'CREATE INDEX idx_sub_workflow_instance_id ON t_ds_relation_sub_workflow (sub_workflow_instance_id)');

  create_index_if_not_exists('task_definition_index',
    'CREATE INDEX task_definition_index ON t_ds_task_definition (project_code, id)');

  create_index_if_not_exists('unique_project_parameter_code',
    'CREATE UNIQUE INDEX unique_project_parameter_code ON t_ds_project_parameter (code)');

  create_index_if_not_exists('unique_project_parameter_name',
    'CREATE UNIQUE INDEX unique_project_parameter_name ON t_ds_project_parameter (project_code, param_name)');

  create_index_if_not_exists('unique_project_preference_code',
    'CREATE UNIQUE INDEX unique_project_preference_code ON t_ds_project_preference (code)');

  create_index_if_not_exists('unique_project_preference_project_code',
    'CREATE UNIQUE INDEX unique_project_preference_project_code ON t_ds_project_preference (project_code)');
END;

BEGIN
  drop_seq_if_exists('t_ds_project_preference_id_sequence');
END;

BEGIN
  create_sequence_if_not_exists('t_ds_project_preference_id_sequence', 'CREATE SEQUENCE t_ds_project_preference_id_sequence START WITH 1 INCREMENT BY 1');
END;

ALTER TABLE t_ds_project_preference MODIFY (id DEFAULT t_ds_project_preference_id_sequence.NEXTVAL);

BEGIN
  drop_seq_if_exists('t_ds_project_parameter_id_sequence');
END;

BEGIN
  create_sequence_if_not_exists('t_ds_project_parameter_id_sequence', 'CREATE SEQUENCE t_ds_project_parameter_id_sequence START WITH 1 INCREMENT BY 1');
END;

ALTER TABLE t_ds_project_parameter MODIFY (id DEFAULT t_ds_project_parameter_id_sequence.NEXTVAL);

BEGIN
  drop_seq_if_exists('t_ds_error_command_id_seq');
END;

COMMENT ON COLUMN t_ds_process_instance.project_code        IS 'project code';
COMMENT ON COLUMN t_ds_process_instance.executor_name       IS 'execute user name';
COMMENT ON COLUMN t_ds_process_instance.tenant_code         IS 'tenant code';
COMMENT ON COLUMN t_ds_task_instance.process_instance_name  IS 'process instance name';
COMMENT ON COLUMN t_ds_task_instance.executor_name          IS 'execute user name';
COMMENT ON COLUMN t_ds_command.tenant_code                  IS 'tenant code';
COMMENT ON COLUMN t_ds_error_command.tenant_code            IS 'tenant code';
COMMENT ON COLUMN t_ds_schedules.tenant_code                IS 'tenant code';

COMMENT ON COLUMN t_ds_alert.sign  IS 'sign=sha1(content)';
