@helpers.sql

BEGIN
  drop_table_if_exists('t_ds_worker_server');
END;
ALTER TABLE T_DS_TASK_INSTANCE MODIFY (LOG_PATH CLOB);


BEGIN
  drop_constraint_if_exists('t_ds_task_instance','foreign_key_instance_id');
END;
BEGIN
  add_constraint_if_not_exists(
    't_ds_task_instance',
    'foreign_key_instance_id',
    q'[ALTER TABLE T_DS_TASK_INSTANCE
       ADD CONSTRAINT FOREIGN_KEY_INSTANCE_ID
       FOREIGN KEY (PROCESS_INSTANCE_ID)
       REFERENCES T_DS_PROCESS_INSTANCE(ID)
       ON DELETE CASCADE]'
  );
END;

-- Add columns safely
BEGIN
  add_column_if_not_exists('t_ds_alert','SIGN',                      'SIGN VARCHAR2(40) DEFAULT '''' NOT NULL');
  add_column_if_not_exists('t_ds_alert','WARNING_TYPE',              'WARNING_TYPE NUMBER(10) DEFAULT 2');
  add_column_if_not_exists('t_ds_user', 'TIME_ZONE',                 'TIME_ZONE VARCHAR2(32)');
  add_column_if_not_exists('t_ds_task_instance','TASK_GROUP_ID',     'TASK_GROUP_ID NUMBER(10)');
  add_column_if_not_exists('t_ds_task_definition','TASK_GROUP_ID',   'TASK_GROUP_ID NUMBER(10)');
  add_column_if_not_exists('t_ds_task_definition','TASK_GROUP_PRIORITY','TASK_GROUP_PRIORITY NUMBER(10) DEFAULT 0');
  add_column_if_not_exists('t_ds_task_definition_log','TASK_GROUP_ID','TASK_GROUP_ID NUMBER(10)');
  add_column_if_not_exists('t_ds_task_definition_log','TASK_GROUP_PRIORITY','TASK_GROUP_PRIORITY NUMBER(10) DEFAULT 0');
  add_column_if_not_exists('t_ds_alert','PROJECT_CODE',              'PROJECT_CODE NUMBER(19)');
  add_column_if_not_exists('t_ds_alert','PROCESS_DEFINITION_CODE',   'PROCESS_DEFINITION_CODE NUMBER(19)');
  add_column_if_not_exists('t_ds_alert','PROCESS_INSTANCE_ID',       'PROCESS_INSTANCE_ID NUMBER(10)');
  add_column_if_not_exists('t_ds_alert','ALERT_TYPE',                'ALERT_TYPE NUMBER(10)');
END;

BEGIN
  create_index_if_not_exists('T_DS_RELATION_PROJECT_USER_UN',
    'CREATE UNIQUE INDEX T_DS_RELATION_PROJECT_USER_UN ON T_DS_RELATION_PROJECT_USER (USER_ID, PROJECT_ID)');
  create_index_if_not_exists('UNIQUE_NAME',
    'CREATE UNIQUE INDEX UNIQUE_NAME ON T_DS_PROJECT (NAME)');
  create_index_if_not_exists('UNIQUE_CODE',
    'CREATE UNIQUE INDEX UNIQUE_CODE ON T_DS_PROJECT (CODE)');
  create_index_if_not_exists('UNIQUE_QUEUE_NAME',
    'CREATE UNIQUE INDEX UNIQUE_QUEUE_NAME ON T_DS_QUEUE (QUEUE_NAME)');
  create_index_if_not_exists('UNIQUE_FUNC_NAME',
    'CREATE UNIQUE INDEX UNIQUE_FUNC_NAME ON T_DS_UDFS (FUNC_NAME)');
  create_index_if_not_exists('UNIQUE_TENANT_CODE',
    'CREATE UNIQUE INDEX UNIQUE_TENANT_CODE ON T_DS_TENANT (TENANT_CODE)');
END;

BEGIN drop_index_if_exists('IDX_TASK_DEFINITION_LOG_PROJECT_CODE'); END;
BEGIN
  create_index_if_not_exists('IDX_TASK_DEFINITION_LOG_PROJECT_CODE',
    'CREATE INDEX IDX_TASK_DEFINITION_LOG_PROJECT_CODE ON T_DS_TASK_DEFINITION_LOG (PROJECT_CODE)');
END;

BEGIN drop_index_if_exists('IDX_TASK_INSTANCE_CODE_VERSION'); END;
BEGIN
  create_index_if_not_exists('IDX_TASK_INSTANCE_CODE_VERSION',
    'CREATE INDEX IDX_TASK_INSTANCE_CODE_VERSION ON T_DS_TASK_INSTANCE (TASK_CODE, TASK_DEFINITION_VERSION)');
END;

BEGIN drop_index_if_exists('IDX_STATUS'); END;
BEGIN
  create_index_if_not_exists('IDX_STATUS',
    'CREATE INDEX IDX_STATUS ON T_DS_ALERT (ALERT_STATUS)');
END;

BEGIN drop_index_if_exists('IDX_SIGN'); END;
BEGIN
  create_index_if_not_exists('IDX_SIGN',
    'CREATE INDEX IDX_SIGN ON T_DS_ALERT (SIGN)');
END;

BEGIN drop_index_if_exists('PROCESS_TASK_RELATION_IDX_PROJECT_CODE_PROCESS_DEFINITION_CODE'); END;
BEGIN
  create_index_if_not_exists('PROCESS_TASK_RELATION_IDX_PROJECT_CODE_PROCESS_DEFINITION_CODE',
    'CREATE INDEX PROCESS_TASK_RELATION_IDX_PROJECT_CODE_PROCESS_DEFINITION_CODE '||
    'ON T_DS_PROCESS_TASK_RELATION (PROJECT_CODE, PROCESS_DEFINITION_CODE)');
END;

BEGIN drop_index_if_exists('PROCESS_TASK_RELATION_IDX_PRE_TASK_CODE_VERSION'); END;
BEGIN
  create_index_if_not_exists('PROCESS_TASK_RELATION_IDX_PRE_TASK_CODE_VERSION',
    'CREATE INDEX PROCESS_TASK_RELATION_IDX_PRE_TASK_CODE_VERSION '||
    'ON T_DS_PROCESS_TASK_RELATION (PRE_TASK_CODE, PRE_TASK_VERSION)');
END;

BEGIN drop_index_if_exists('PROCESS_TASK_RELATION_IDX_POST_TASK_CODE_VERSION'); END;
BEGIN
  create_index_if_not_exists('PROCESS_TASK_RELATION_IDX_POST_TASK_CODE_VERSION',
    'CREATE INDEX PROCESS_TASK_RELATION_IDX_POST_TASK_CODE_VERSION '||
    'ON T_DS_PROCESS_TASK_RELATION (POST_TASK_CODE, POST_TASK_VERSION)');
END;

BEGIN drop_index_if_exists('PROCESS_TASK_RELATION_LOG_IDX_PROJECT_CODE_PROCESS_DEFINITION_CODE'); END;
BEGIN
  create_index_if_not_exists('PROCESS_TASK_RELATION_LOG_IDX_PROJECT_CODE_PROCESS_DEFINITION_CODE',
    'CREATE INDEX PROCESS_TASK_RELATION_LOG_IDX_PROJECT_CODE_PROCESS_DEFINITION_CODE '||
    'ON T_DS_PROCESS_TASK_RELATION_LOG (PROJECT_CODE, PROCESS_DEFINITION_CODE)');
END;

BEGIN drop_index_if_exists('IDX_TASK_DEFINITION_LOG_CODE_VERSION'); END;
BEGIN
  create_index_if_not_exists('IDX_TASK_DEFINITION_LOG_CODE_VERSION',
    'CREATE INDEX IDX_TASK_DEFINITION_LOG_CODE_VERSION ON T_DS_TASK_DEFINITION_LOG (CODE, VERSION)');
END;

BEGIN drop_index_if_exists('USER_ID_INDEX'); END;
BEGIN
  create_index_if_not_exists('USER_ID_INDEX',
    'CREATE INDEX USER_ID_INDEX ON T_DS_PROJECT (USER_ID)');
END;
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
-- 4. CREATE TABLES (IF NOT EXISTS)
-------------------------------------------------------------------------------

BEGIN
  create_table_if_not_exists('T_DS_DQ_COMPARISON_TYPE', q'[
    CREATE TABLE T_DS_DQ_COMPARISON_TYPE (
      ID               NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
      "TYPE"           VARCHAR2(255) NOT NULL,
      EXECUTE_SQL      CLOB,
      OUTPUT_TABLE     VARCHAR2(255),
      "NAME"           VARCHAR2(255),
      CREATE_TIME      TIMESTAMP(6),
      UPDATE_TIME      TIMESTAMP(6),
      IS_INNER_SOURCE  NUMBER(1) CHECK (IS_INNER_SOURCE IN (0,1)),
      CONSTRAINT T_DS_DQ_COMPARISON_TYPE_PK PRIMARY KEY (ID)
    )
  ]');
END;

BEGIN
  create_table_if_not_exists('T_DS_DQ_EXECUTE_RESULT', q'[
    CREATE TABLE T_DS_DQ_EXECUTE_RESULT (
      ID                   NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
      PROCESS_DEFINITION_ID NUMBER(10),
      PROCESS_INSTANCE_ID  NUMBER(10),
      TASK_INSTANCE_ID     NUMBER(10),
      RULE_TYPE            NUMBER(10),
      RULE_NAME            VARCHAR2(255),
      STATISTICS_VALUE     NUMBER(18,8),
      COMPARISON_VALUE     NUMBER(18,8),
      CHECK_TYPE           NUMBER(10),
      THRESHOLD            NUMBER(18,8),
      "OPERATOR"           NUMBER(10),
      FAILURE_STRATEGY     NUMBER(10),
      STATE                NUMBER(10),
      USER_ID              NUMBER(10),
      CREATE_TIME          TIMESTAMP(6),
      UPDATE_TIME          TIMESTAMP(6),
      COMPARISON_TYPE      NUMBER(10),
      ERROR_OUTPUT_PATH    CLOB,
      CONSTRAINT T_DS_DQ_EXECUTE_RESULT_PK PRIMARY KEY (ID)
    )
  ]');
END;

BEGIN
  create_table_if_not_exists('T_DS_DQ_RULE', q'[
    CREATE TABLE T_DS_DQ_RULE (
      ID          NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
      "NAME"      VARCHAR2(100),
      "TYPE"      NUMBER(10),
      USER_ID     NUMBER(10),
      CREATE_TIME TIMESTAMP(6),
      UPDATE_TIME TIMESTAMP(6),
      CONSTRAINT T_DS_DQ_RULE_PK PRIMARY KEY (ID)
    )
  ]');
END;

BEGIN
  create_table_if_not_exists('T_DS_DQ_RULE_EXECUTE_SQL', q'[
    CREATE TABLE T_DS_DQ_RULE_EXECUTE_SQL (
      ID                   NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
      "INDEX"              NUMBER(10),
      "SQL"                CLOB,
      TABLE_ALIAS          VARCHAR2(255),
      "TYPE"               NUMBER(10),
      CREATE_TIME          TIMESTAMP(6),
      UPDATE_TIME          TIMESTAMP(6),
      IS_ERROR_OUTPUT_SQL  NUMBER(1) CHECK (IS_ERROR_OUTPUT_SQL IN (0,1)),
      CONSTRAINT T_DS_DQ_RULE_EXECUTE_SQL_PK PRIMARY KEY (ID)
    )
  ]');
END;

BEGIN
  create_table_if_not_exists('T_DS_DQ_RULE_INPUT_ENTRY', q'[
    CREATE TABLE T_DS_DQ_RULE_INPUT_ENTRY (
      ID                 NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
      FIELD              VARCHAR2(255),
      "TYPE"             VARCHAR2(255),
      TITLE              VARCHAR2(255),
      VALUE              VARCHAR2(255),
      "OPTIONS"          CLOB,
      PLACEHOLDER        VARCHAR2(255),
      OPTION_SOURCE_TYPE NUMBER(10),
      VALUE_TYPE         NUMBER(10),
      INPUT_TYPE         NUMBER(10),
      IS_SHOW            NUMBER(5) DEFAULT 1,
      CAN_EDIT           NUMBER(5) DEFAULT 1,
      IS_EMIT            NUMBER(5) DEFAULT 0,
      IS_VALIDATE        NUMBER(5) DEFAULT 0,
      CREATE_TIME        TIMESTAMP(6),
      UPDATE_TIME        TIMESTAMP(6),
      CONSTRAINT T_DS_DQ_RULE_INPUT_ENTRY_PK PRIMARY KEY (ID)
    )
  ]');
END;

BEGIN
  create_table_if_not_exists('T_DS_DQ_TASK_STATISTICS_VALUE', q'[
    CREATE TABLE T_DS_DQ_TASK_STATISTICS_VALUE (
      ID                    NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
      PROCESS_DEFINITION_ID NUMBER(10) NOT NULL,
      TASK_INSTANCE_ID      NUMBER(10),
      RULE_ID               NUMBER(10) NOT NULL,
      UNIQUE_CODE           VARCHAR2(255) NOT NULL,
      STATISTICS_NAME       VARCHAR2(255),
      STATISTICS_VALUE      NUMBER(18,8),
      DATA_TIME             TIMESTAMP(0),
      CREATE_TIME           TIMESTAMP(0),
      UPDATE_TIME           TIMESTAMP(0),
      CONSTRAINT T_DS_DQ_TASK_STATISTICS_VALUE_PK PRIMARY KEY (ID)
    )
  ]');
END;

BEGIN
  create_table_if_not_exists('T_DS_RELATION_RULE_EXECUTE_SQL', q'[
    CREATE TABLE T_DS_RELATION_RULE_EXECUTE_SQL (
      ID             NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
      RULE_ID        NUMBER(10),
      EXECUTE_SQL_ID NUMBER(10),
      CREATE_TIME    TIMESTAMP(6),
      UPDATE_TIME    TIMESTAMP(6),
      CONSTRAINT T_DS_RELATION_RULE_EXECUTE_SQL_PK PRIMARY KEY (ID)
    )
  ]');
END;

BEGIN
  create_table_if_not_exists('T_DS_RELATION_RULE_INPUT_ENTRY', q'[
    CREATE TABLE T_DS_RELATION_RULE_INPUT_ENTRY (
      ID                 NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
      RULE_ID            NUMBER(10),
      RULE_INPUT_ENTRY_ID NUMBER(10),
      VALUES_MAP         CLOB,
      "INDEX"            NUMBER(10),
      CREATE_TIME        TIMESTAMP(6),
      UPDATE_TIME        TIMESTAMP(6),
      CONSTRAINT T_DS_RELATION_RULE_INPUT_ENTRY_PK PRIMARY KEY (ID)
    )
  ]');
END;

BEGIN
  create_table_if_not_exists('T_DS_K8S', q'[
    CREATE TABLE T_DS_K8S (
      ID          NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
      K8S_NAME    VARCHAR2(100),
      K8S_CONFIG  CLOB,
      CREATE_TIME TIMESTAMP(6),
      UPDATE_TIME TIMESTAMP(6),
      CONSTRAINT T_DS_K8S_PK PRIMARY KEY (ID)
    )
  ]');
END;

BEGIN
  create_table_if_not_exists('T_DS_K8S_NAMESPACE', q'[
    CREATE TABLE T_DS_K8S_NAMESPACE (
      ID                  NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
      LIMITS_MEMORY       NUMBER(10),
      NAMESPACE           VARCHAR2(100),
      ONLINE_JOB_NUM      NUMBER(10) DEFAULT 0,
      USER_ID             NUMBER(10),
      POD_REPLICAS        NUMBER(10),
      POD_REQUEST_CPU     NUMBER(13,4),
      POD_REQUEST_MEMORY  NUMBER(10),
      LIMITS_CPU          NUMBER(13,4),
      K8S                 VARCHAR2(100),
      CREATE_TIME         TIMESTAMP(6),
      UPDATE_TIME         TIMESTAMP(6),
      CONSTRAINT T_DS_K8S_NAMESPACE_PK PRIMARY KEY (ID),
      CONSTRAINT K8S_NAMESPACE_UNIQUE UNIQUE (NAMESPACE, K8S)
    )
  ]');
END;

BEGIN
  create_table_if_not_exists('T_DS_RELATION_NAMESPACE_USER', q'[
    CREATE TABLE T_DS_RELATION_NAMESPACE_USER (
      ID           NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
      USER_ID      NUMBER(10),
      NAMESPACE_ID NUMBER(10),
      PERM         NUMBER(10),
      CREATE_TIME  TIMESTAMP(6),
      UPDATE_TIME  TIMESTAMP(6),
      CONSTRAINT T_DS_RELATION_NAMESPACE_USER_PK PRIMARY KEY (ID),
      CONSTRAINT NAMESPACE_USER_UNIQUE UNIQUE (USER_ID, NAMESPACE_ID)
    )
  ]');
END;

BEGIN
  create_table_if_not_exists('T_DS_ALERT_SEND_STATUS', q'[
    CREATE TABLE T_DS_ALERT_SEND_STATUS (
      ID                       NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
      ALERT_ID                 NUMBER(10) NOT NULL,
      ALERT_PLUGIN_INSTANCE_ID NUMBER(10) NOT NULL,
      SEND_STATUS              NUMBER(10) DEFAULT 0,
      LOG                      CLOB,
      CREATE_TIME              TIMESTAMP(6),
      CONSTRAINT T_DS_ALERT_SEND_STATUS_PK PRIMARY KEY (ID),
      CONSTRAINT ALERT_SEND_STATUS_UNIQUE UNIQUE (ALERT_ID, ALERT_PLUGIN_INSTANCE_ID)
    )
  ]');
END;

BEGIN
  create_table_if_not_exists('T_DS_AUDIT_LOG', q'[
    CREATE TABLE T_DS_AUDIT_LOG (
      ID            NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
      USER_ID       NUMBER(10) NOT NULL,
      RESOURCE_TYPE NUMBER(10) NOT NULL,
      OPERATION     NUMBER(10) NOT NULL,
      TIME          TIMESTAMP(6),
      RESOURCE_ID   NUMBER(10) NOT NULL,
      CONSTRAINT T_DS_AUDIT_LOG_PK PRIMARY KEY (ID)
    )
  ]');
END;

BEGIN
  create_table_if_not_exists('T_DS_TASK_GROUP', q'[
    CREATE TABLE T_DS_TASK_GROUP (
      ID           NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
      NAME         VARCHAR2(100),
      DESCRIPTION  VARCHAR2(200),
      GROUP_SIZE   NUMBER(10) NOT NULL,
      PROJECT_CODE NUMBER(19) DEFAULT 0,
      USE_SIZE     NUMBER(10) DEFAULT 0,
      USER_ID      NUMBER(10),
      STATUS       NUMBER(10) DEFAULT 1,
      CREATE_TIME  TIMESTAMP(6),
      UPDATE_TIME  TIMESTAMP(6),
      CONSTRAINT T_DS_TASK_GROUP_PK PRIMARY KEY (ID)
    )
  ]');
END;

BEGIN
  create_table_if_not_exists('T_DS_TASK_GROUP_QUEUE', q'[
    CREATE TABLE T_DS_TASK_GROUP_QUEUE (
      ID            NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
      TASK_ID       NUMBER(10),
      TASK_NAME     VARCHAR2(100),
      GROUP_ID      NUMBER(10),
      PROCESS_ID    NUMBER(10),
      PRIORITY      NUMBER(10) DEFAULT 0,
      STATUS        NUMBER(10) DEFAULT -1,
      FORCE_START   NUMBER(10) DEFAULT 0,
      IN_QUEUE      NUMBER(10) DEFAULT 0,
      CREATE_TIME   TIMESTAMP(6),
      UPDATE_TIME   TIMESTAMP(6),
      CONSTRAINT T_DS_TASK_GROUP_QUEUE_PK PRIMARY KEY (ID)
    )
  ]');
END;

BEGIN
  create_index_if_not_exists('IDX_T_DS_TASK_GROUP_QUEUE_IN_QUEUE',
    'CREATE INDEX IDX_T_DS_TASK_GROUP_QUEUE_IN_QUEUE ON T_DS_TASK_GROUP_QUEUE (IN_QUEUE)');
END;

COMMIT;
